apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: aoki-test
  namespace: sandbox
  annotations:
    metric-config.external.ready-pods-autoscale.prometheus/query: |
      scalar(sum(webapp_server_ready==0) OR on() vector(0) + 3)
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aoki-test
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: External
    external:
      metric:
        name: ready-pods-autoscale
        selector:
          matchLabels:
            type: prometheus  # required
      target:
        type: AverageValue
        averageValue: 3
