apiVersion: v1
kind: Service
metadata:
  namespace: sandbox
  name: aoki-test
spec:
  selector:
    app: aoki-test
  ports:
  - protocol: TCP
    port: 80  # Pod で特権 port に bind しなくても、Service ではつけられる
    targetPort: http
